# Generated by Django 5.2.4 on 2025-07-30 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_order_date_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 7, 30, 13, 42, 45, 134754)
            ),
        ),
    ]
