# Generated by Django 5.2.4 on 2025-07-31 14:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_product_is_sale_product_sale_price_alter_order_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="star",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxLengthValidator(5),
                    django.core.validators.MinLengthValidator(0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 7, 31, 14, 43, 44, 77878)
            ),
        ),
    ]
